package com.sample.kvservice.dao;

import com.sample.kvservice.PostgressApplication;
import com.sample.kvservice.entity.Node;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = PostgressApplication.class)
@ActiveProfiles("test")
public class NodeDaoTest {

    @Autowired
    NodeDao nodeDao;

    @Test
    public void testCreateNode(){
        Node node = new Node();
        node.setDbCapacity(50);
        node.setHostname("localhost");
        node.setLoadFactor(80);
        node.setHealthy(true);

        Node createdNode = nodeDao.saveNode(node);
        assertNotNull(createdNode);

        // Autogenerated id should be assigned
        assertNotNull(createdNode.getId());
        assertEquals(node.getHostname(), createdNode.getHostname());
        assertEquals(node.getDbCapacity(), createdNode.getDbCapacity());
        assertEquals(node.getLoadFactor(), createdNode.getLoadFactor());
        assertEquals(node.getHealthy(), createdNode.getHealthy());

    }

    @Test
    public void testGetAllNodes(){

        for(int i=0; i<10; i++){
            Node node = new Node();
            node.setDbCapacity(i);
            node.setHostname("localhost"+i);
            node.setLoadFactor(i);
            node.setHealthy(true);

            nodeDao.saveNode(node);
        }

        List<Node> allNodes = nodeDao.getAllNodes();
        assertNotNull(allNodes);
        assertEquals(10, allNodes.size());

    }

}
